spring:
  profiles:
    active: local
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seoul?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: dbsl3761
  devtools:
    livereload:
      enabled: true

server:
  port: 7000
